"""auto vote

Revision ID: d32e96ec445d
Revises: f2a9315caa61
Create Date: 2021-11-19 15:51:10.066246

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd32e96ec445d'
down_revision = 'f2a9315caa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(('post_id',), ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(('user_id',), ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
